plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = project.mod_version
group = mod_group

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

processResources {
    exclude '.cache/'

    def replaceProperties = [
        version               : project.version,
        mod_id                : mod_id,
        mod_name              : mod_name,
        mod_license           : mod_license,
        mod_url               : mod_url,
        mod_update            : mod_update,
        mod_tracker           : mod_tracker,
        mod_credits           : mod_credits,
        mod_authors           : mod_authors,
        mod_description       : mod_description,
        minecraft_version     : minecraft_version,
        minecraft_version_range: minecraft_version_range,
        loader_version        : loader_version
    ]

    inputs.properties replaceProperties
    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net" }
    maven { url = "https://maven.theillusivec4.top/" }
    maven { url = "https://maven.blamejared.com" }
    maven { url = "https://maven.shedaniel.me/" }
    maven { url = "https://maven.architectury.dev/" }
    maven { url = "https://repo.essential.gg/public" }
    maven { url = "https://cursemaven.com" }
    maven { url = "https://jitpack.io" }
    maven { url = "https://packages.aether-mod.net/Nitrogen" }
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    modImplementation "com.aetherteam.nitrogen:nitrogen_internals:${project.nitrogen_version}"
    modImplementation "gg.essential:partner-mod-integration-1.21.1-fabric:${project.essential_partner_integration_version}"

    runtimeOnly "io.github.flemmli97:debugutils:1.21-${project.debugutils_version}-fabric"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"

    modCompileOnly "mezz.jei:jei-1.21.11-common-api:${project.jei_version}"
    modCompileOnly "mezz.jei:jei-1.21.11-fabric-api:${project.jei_version}"

    modCompileOnly "curse.maven:jade-324717:${project.jade_version}"
    modCompileOnly "curse.maven:lootr-361276:${project.lootr_version}"

    modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
    modCompileOnly "me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}"
    modCompileOnly "dev.architectury:architectury-fabric:${architectury_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xmaxerrs' << '400'
}

compileJava {
    options.incremental = false
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            name = 'GitHubPackages'
            url = 'https://maven.pkg.github.com/The-Aether-Team/The-Aether-fabric'
            credentials {
                username = System.getenv('GITHUB_ACTOR')
                password = System.getenv('GITHUB_TOKEN')
            }
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
